version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    env_file:
      - config/db-hml.env

  api-cake-hml:
    depends_on:
      - db
    build: .
    ports:
      - "8083:8083"
    restart: always

volumes:
  db_data: {}