version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    env_file:
      - config/db-prod.env

  api-cake-prod:
    depends_on:
      - db
    build: .
    ports:
      - "8084:8084"
    restart: always

volumes:
  db_data: {}